{
  description = "Logos Pilot Module";

  inputs = {
    # Pinned, not floating: the lez_core module (033f807a) is generated by a NEWER generator
    # whose client headers include logos_call_error.h — added to logos-cpp-sdk on 2026-08-03.
    # Our April builder shipped an SDK without it, so the pilot failed to compile the generated
    # lez_core client. ddddd8cc (2026-08-07) is the builder that re-pins the whole SDK stack to
    # match. Keep this in step with the lez_core pin below.
    logos-module-builder.url = "github:logos-co/logos-module-builder/ddddd8cc4025";
    nix-bundle-lgx.url = "github:logos-co/nix-bundle-lgx";
    lez_core.url = "github:logos-blockchain/logos-execution-zone-module/033f807a3b1690fb2f8e661cb8067646b8a98242";
    delivery_module.url = "github:logos-co/logos-delivery-module";
    storage_module.url = "github:logos-co/logos-storage-module";
    waku_module.url = "github:logos-co/logos-waku-module";
    chat_module.url = "github:logos-co/logos-chat-module";
  };

  outputs = inputs@{ logos-module-builder, ... }:
    logos-module-builder.lib.mkLogosModule {
      src = ./.;
      configFile = ./metadata.json;
      flakeInputs = inputs;
      preConfigure = ''
        logos-cpp-generator --from-header src/pilot_impl.h \
          --backend qt \
          --impl-class PilotImpl \
          --impl-header pilot_impl.h \
          --metadata metadata.json \
          --output-dir ./generated_code

        # The generator does NOT produce an onInit wrapper (we removed it from
        # the impl header). Inject an override so the framework can pass the
        # LogosAPI pointer to PilotImpl when the module loads.
        sed -i '/^private:/i\    void onInit(LogosAPI* api) override {\n        m_impl.logosAPI_ = api;\n    }\n' \
          ./generated_code/pilot_qt_glue.h
      '';
    };
}
